export const ROLES = {
  OWNER: 'owner',
  ADMIN: 'admin',
  DISPATCHER: 'dispatcher',
  VIEWER: 'viewer',
  ACCOUNTANT: 'accountant',
} as const;

export const ROLE_LABELS = {
  [ROLES.OWNER]: 'صاحب الحساب',
  [ROLES.ADMIN]: 'مسؤول',
  [ROLES.DISPATCHER]: 'موزع',
  [ROLES.VIEWER]: 'عارض',
  [ROLES.ACCOUNTANT]: 'محاسب',
} as const;

export const ROLE_PERMISSIONS = {
  [ROLES.OWNER]: {
    canViewVehicles: true,
    canAddVehicles: true,
    canDeleteVehicles: true,
    canViewTrips: true,
    canViewReports: true,
    canManageUsers: true,
    canManageGeofences: true,
    canViewBilling: true,
    canManageSubscription: true,
    canViewSupport: true,
    canCreateSupport: true,
  },
  [ROLES.ADMIN]: {
    canViewVehicles: true,
    canAddVehicles: true,
    canDeleteVehicles: true,
    canViewTrips: true,
    canViewReports: true,
    canManageUsers: false,
    canManageGeofences: true,
    canViewBilling: false,
    canManageSubscription: false,
    canViewSupport: true,
    canCreateSupport: true,
  },
  [ROLES.DISPATCHER]: {
    canViewVehicles: true,
    canAddVehicles: false,
    canDeleteVehicles: false,
    canViewTrips: true,
    canViewReports: false,
    canManageUsers: false,
    canManageGeofences: false,
    canViewBilling: false,
    canManageSubscription: false,
    canViewSupport: false,
    canCreateSupport: true,
  },
  [ROLES.VIEWER]: {
    canViewVehicles: true,
    canAddVehicles: false,
    canDeleteVehicles: false,
    canViewTrips: true,
    canViewReports: false,
    canManageUsers: false,
    canManageGeofences: false,
    canViewBilling: false,
    canManageSubscription: false,
    canViewSupport: false,
    canCreateSupport: false,
  },
  [ROLES.ACCOUNTANT]: {
    canViewVehicles: false,
    canAddVehicles: false,
    canDeleteVehicles: false,
    canViewTrips: false,
    canViewReports: false,
    canManageUsers: false,
    canManageGeofences: false,
    canViewBilling: true,
    canManageSubscription: true,
    canViewSupport: false,
    canCreateSupport: false,
  },
} as const;
